### ISSUE TITLE
Review Ticket

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/Tri-2-CSA-Project#11]
- [x] Design - Wiki Theme, Brain Write & Wire Frame

  - [x] Technicals - 10 to 12 key ideas
  
  - [x] Github - On Wiki containing Management Plan, forking, branching, pull request, etc

 - [x]  Deployment - On Wiki containing Hardware, frequency, etc

  - [x] Scrum Board - Assignments and Backlog

**Comment by ChristopherDuroiu** [comment]
Design - Wireframe missing -0.2
Technicals - Great technical all have great potential. I would like to see them in the repo as well. 
Github - Established and ready to work
Deployment - The deployment plan is very specific and thorough
Scrum Board - All tasks are thorough and have individual assignees. Nice job

4.8/5

**Comment by jm1021** [comment]
Rugged Boys - Rishi 4.5/5
* Central repository for campus resources, no wire.8/1
* Ideas are not describe in technical relation .9/1
* More specific or visual added to GitHub. .9/1
    * How to avoid crisis on delivery day 
* Instructions seem short, nothing on frequency .9/1
* Scrum board looks active and though out 1/1
