### ISSUE TITLE
Begin thinking of the technical features we want to have in the project

### ISSUE THREAD

**Issue by ArnavPalkhiwala** [rpeddakama/Tri-2-CSA-Project#5]
- [ ] This comes after we come up with an idea so we can add more detail to it and decide what we want it to do

**Comment by rpeddakama** [comment]
Google doc with our brainstorming can be viewed [here](https://docs.google.com/document/d/1XQkpwQTJAoKGqRqClHZkZZvJ2bQtxxvdSr6sWpZIdHI/edit?usp=sharing)
