### ISSUE TITLE
Raadwan's AP FRQs Review Ticket

### ISSUE THREAD

**Issue by raad1masum** [rpeddakama/Tri-2-CSA-Project#50]

**Comment by raad1masum** [comment]
### [**Wiki with everything in it**](https://github.com/rpeddakama/Tri-2-CSA-Project/wiki/Raadwan-Masum-FRQ-Takeaways)

**Comment by adritac-tech** [comment]
# Crossover Grading
**Grading For:** Raadwan Masum
**Graded By:** Adrita Chakraborty

## TOTAL SCORE: 9/10

| FRQ | Evaluation | Score |
| --- | --- | --- |
| Unit 2 | Good input - easy to follow instructions and see resulting output | 1.5/1.5 |
| Unit 3 | Easy input - output was kind of basic and repeated the line lengths that were inputted (maybe including an Ascii visual or some other element for next time?) | 1/1.5 |
| Unit 4 | Great output and input - accurate after many trials | 1/1 |
| Unit 5 | Good input and output - easy to use | 1/1 |
| Unit 6 | Good output - clear and concise (maybe next time include the original list to show that it effectively sorted, but code was clear so good job) | 1/1 |
| Unit 7 | Great input and output | 1/1 |
| Unit 8 | Good output, clear what the code is doing - code itself is very efficient | 1/1 |
| Unit 9 | Good output, clearly accomplishes goal of the FRQ | 1/1 |
| Unit 10 | Great input and output. Works after multiple attempts | 1/1 |

### Github Wiki
* GitHub wiki is easy to use and navigate
* Runtime is placed in a clear location that is easy to access
* Good takeaways from each unit

### Design & 2 Inputs
* Much more than 2 inputs 
* All FRQs have cohesive and efficient code 
* Runtime runs smoothly with no complications (easy to understand for the user)

### Overall Grading / Comments
* 9 FRQs - 8.5/9
* Extra point - 0.5/1 
* Total score - 9/10
* **Each Individual has GitHub of source for every FRQ that is integrated with Deployed Java/Spring or Replit** (did not see GitHub source for the Replit)

**Comment by raad1masum** [comment]
# Analysis and Reflection
- Both of our FRQ 3s had similar code execution. I think we both could have done more work to add interesting features to that one.
- I liked my FRQ 10 best out of my FRQs, but I liked FRQ 4 of Adrita's work.
- Both of us had some runtime errors with input, there was no error handling for types.
